//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Carteleras
    {
        public int IdCartelera { get; set; }
        [Required]
        public int IdSede { get; set; }
        [Required]
        public int IdPelicula { get; set; }
        [Required]
        [Range(15,23,ErrorMessage ="Hora Inicio no puede ser anterior a las 15 hs")]
        public int HoraInicio { get; set; }
        [Required]
        public System.DateTime FechaInicio { get; set; }
        [Required]
        public System.DateTime FechaFin { get; set; }
        [Required]
        [StringLength(2)]
        public int NumeroSala { get; set; }
        [Required]
        public int IdVersion { get; set; }
        [Required]
        public bool Lunes { get; set; }
        [Required]
        public bool Martes { get; set; }
        [Required]
        public bool Miercoles { get; set; }
        [Required]
        public bool Jueves { get; set; }
        [Required]
        public bool Viernes { get; set; }
        [Required]
        public bool Sabado { get; set; }
        [Required]
        public bool Domingo { get; set; }
        [Required]
        public System.DateTime FechaCarga { get; set; }
    
        public virtual Peliculas Peliculas { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual Versiones Versiones { get; set; }
    }
}
