//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sedes
    {
        public Sedes()
        {
            this.Carteleras = new HashSet<Carteleras>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdSede { get; set; }
        [Required(ErrorMessage = "Complete Nombre")]
        [StringLength(100, ErrorMessage = "Ha sobrepasado el límite de caracteres permitidos")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Complete Dirección")]
        [StringLength(300, ErrorMessage = "Ha sobrepasado el límite de caracteres permitidos")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "Complete Precio de Entrada")]
        [Range(0.05,999999999999999999.99,ErrorMessage ="Ha sobrepasado el valor permitido o el mismo es menor a 0,05")]
        public decimal PrecioGeneral { get; set; }
        public virtual ICollection<Carteleras> Carteleras { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
