//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        [StringLength(50, ErrorMessage = "Ha sobrepasado el límite de caracteres permitidos")]
        public string NombreUsuario { get; set; }
        [StringLength(50, ErrorMessage = "Ha sobrepasado el límite de caracteres permitidos")]
        public string Password { get; set; }
    }
}
